Fix Qt5 QInputDialog parameter: mode → echo
In Qt5, QInputDialog.getText() changed the parameter name:
- Qt4: mode=QLineEdit.Password
- Qt5: echo=QLineEdit.Password

This fixes the SLURM authentication dialog which was failing with:
TypeError: 'mode' is not a valid keyword argument

Now the password dialog will appear correctly when running cluster jobs.